img.youtube.com
.*\.onion.*
.*\.mcretro\.net
retrojunkie\.net
gieskes\.nl
autourdupc\.com
hdat2\.com
fatcat\.co\.nz
outbreak\.gov\.au
macintoshgarden\.org
.*/homepages/.*
https?://retrojunkie\.net/.*
https?://www\.gieskes\.nl/.*
https?://www\.autourdupc\.com/.*
https?://www\.fatcat\.co\.nz/.*
https?://web\.archive\.org/web/20120712033436/.*
https?://web\.archive\.org/web/20030308205428/.*
https?://web\.archive\.org/web/20010412185405/.*
https?://www\.hdat2\.com/.*
https?://www\.outbreak\.gov\.au/.*
https?://macintoshgarden\.org/.*
https?://geocities\.mcretro\.net/.*
https?://mcretro\.net/homepages/.*
https?://mcretro\.net/tools/.*